// src/constants/errorCodes.js

export const ERROR_CODES = {
  // SEO
  SEO_TITLE_TOO_LONG: "SEO_TITLE_TOO_LONG",
  SEO_DESCRIPTION_TOO_LONG: "SEO_DESCRIPTION_TOO_LONG",

  // General validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // RBAC (sudah dipakai)
  AUTH_REQUIRED: "AUTH_REQUIRED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  WORKSPACE_REQUIRED: "WORKSPACE_REQUIRED",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  FORBIDDEN_NO_ROLE: "FORBIDDEN_NO_ROLE",
  FORBIDDEN_NO_PERMISSION: "FORBIDDEN_NO_PERMISSION",

  // Plan (E section, nanti)
  // PLAN_LIMIT_EXCEEDED: "PLAN_LIMIT_EXCEEDED",
};
