export const MODULE_KEYS = {
  AUTH: "AUTH",

  USERS: "USERS",
  WORKSPACES: "WORKSPACES",
  ROLES: "ROLES",
  PERMISSIONS: "PERMISSIONS",

  CONTENT_TYPES: "CONTENT_TYPES",
  CONTENT_FIELDS: "CONTENT_FIELDS",
  CONTENT_ENTRIES: "CONTENT_ENTRIES",
  CONTENT_RELATIONS: "CONTENT_RELATIONS",
  CONTENT_SEO: "CONTENT_SEO",

  PLANS: "PLANS",
  SUBSCRIPTIONS: "SUBSCRIPTIONS",
  BILLING: "BILLING",

  PRODUCTS: "PRODUCTS",
  BRANDS: "BRANDS",

  ASSETS: "ASSETS",
  UPLOADS: "UPLOADS",
};
