export const ACTIONS = {
  CREATE: "CREATE",
  READ: "READ",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  PUBLISH: "PUBLISH",
  ALL: "ALL", // ✅ untuk wildcard
};

export const RESOURCES = {
  USERS: "USERS",
  WORKSPACES: "WORKSPACES",
  CONTENT_TYPES: "CONTENT_TYPES",
  CONTENT_FIELDS: "CONTENT_FIELDS",
  CONTENT_ENTRIES: "CONTENT_ENTRIES",
  BRANDS: "BRANDS",
  PRODUCTS: "PRODUCTS",
  PLANS: "PLANS",
  ROLES: "ROLES",
  PERMISSIONS: "PERMISSIONS",
  UPLOADS: "UPLOADS",
  ASSETS: "ASSETS", // ✅ Media Library
  ALL: "ALL", // ✅ untuk wildcard
};
